# Default values for ingester.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 2
image:
  repository: coco/people-rw-neo4j
  version: v0.1.7
  pullPolicy: Always
people_rw_neo4j:
  graphite_address: "graphite.ft.com"
  graphite_prefix: "coco.services.k8s.people-rw-neo4j-red"
  batch_size: "10"
  neo_url: "http://neo4j-red:7474/db/data/"
 
service:
  name: people-rw-neo4j
  hasHealthcheck: "true"
resources:
  limits:
    memory: 1Gi

